name: food101-EfficientNet_B2        
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12.3           
  - pytorch=2.5.1           
  - torchvision=0.20.1      
  - pip                  
  - pip:
    - sagemaker[local]==2.213.0
    - tqdm
    - PyYAML
    - ruff      
    - python-dotenv         
