estimator:
  hyperparameters:
    seed: 42
    batch-size: 128
    num-epochs-phase1: 8
    num-epochs-phase2: 10
    lr-head: 4e-3
    lr-backbone: 5e-4
    patience: 3
    num-workers: 2
    img-size: 224
  instance_count: 1
  instance_type: "ml.g4dn.xlarge"
  framework_version: "2.6.0"
  py_version: "py312"
  base_job_name: "food101-classifier"
  use_spot_instances: true
  max_run: 10800    # seconds
  max_wait: 14400   # seconds, needed when using spot instances or otherwise wait indefinitely