estimator:
  hyperparameters:
    seed: 42
    batch_size: 1024
    num_epochs_phase1: 6
    num_epochs_phase2: 3
    lr_head: 0.001
    lr_backbone: 0.001
    patience: 3
    num_workers: 3
    img_size: 224
  instance_count: 1
  instance_type: "ml.m5.xlarge"
  framework_version: "2.2.0"
  py_version: "py310"
  base_job_name: "mnist-cnn"
  use_spot_instances: true
  max_run: 7200     # seconds
  max_wait: 14400   # seconds, needed when using spot instances or otherwise wait indefinitely