estimator:
  hyperparameters:
    epochs: 6
    lr: 0.001
    batch: 1024
  instance_count: 1
  instance_type: "ml.m5.xlarge"
  framework_version: "2.2.0"
  py_version: "py310"
  base_job_name: "mnist-cnn"
  use_spot_instances: true
  max_run: 7200     # seconds
  max_wait: 14400   # seconds, needed when using spot instances or otherwise wait indefinitely